export const showcaseExamples = [
  {
    title: 'Live ceremony captioning',
    task: 'Audio-visual captioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=5K11NVOcQnQ',
    embedUrl: 'https://www.youtube-nocookie.com/embed/5K11NVOcQnQ',
    prompt:
      'Generate a comprehensive caption that describes the visuals, background sounds, music, and spoken dialogue of the given video.',
    response: `The video opens with a dynamic animated graphic featuring the Fox News logo and the text 'ALERT' in bold red and yellow, transitioning to a live broadcast from Washington, D.C. at 9:20 AM ET. A man in a dark suit and red tie stands at a podium with the Presidential Seal, flanked by American flags and official flags, as a 'BREAKING NEWS' banner reads 'SOON: RUBIO SWORN IN AS TRUMP KICKSTARTS NEW ERA.' JD Vance, the Vice President, addresses the audience, saying, 'Thank you. We have JD Vance, the Vice President. He's about to swear in Marco Rubio to be Secretary of State and his wife.' Marco Rubio, in a dark suit and patterned tie, stands beside Vance, with a woman in a pink dress holding a Bible. Vance continues, 'Thank you guys for being here. It's a great occasion. I will say that it's pretty hard to top being sworn in as Vice President and then the Buckeyes win the national championship the very same day.' He adds, 'But this is a hell of a start to a run because Marco is one of my favorite people in Washington. And you know, he's a son of Cuban immigrants to this country. He grew up in very humble beginnings, but he has an incredibly deep love of our nation.' Vance states, 'He is a bipartisan solutions seeker, a guy who can actually get things done, but a conservative of great principle and great vision. And I think more than almost any potty that I've met in Washington the last few years, Senator Rubio, I think understands the distinctive priorities of President Trump and why it represents such a significant and frankly important and needed departure from a generation of failed foreign policy.' He concludes, 'Senator Rubio will be the chief diplomat of the United States of America, but he will remain a friend. I'm proud to know him, and I'm proud to do this. So, Senator Rubio, thank you.'

The scene shifts to the swearing-in ceremony. Vance says, 'I also, of course, want to thank President Trump for nominating Senator Rubio and giving me a first easy swearing-in. That's the first time I've ever sworn in an official in the United States government. And I want to thank Senator Jim Risch and his family for making this easy. You guys got this done and got it done very quickly. 99 to zero, right? I think even I wouldn't have got close to 99 to zero. So, Senator Rubio, it's a great testament to your career of service, and this is a new chapter, man, but I think you're going to do great.' He adds, 'So, great. So, I think that we're going to administer the oath, and then Senator, you'll say a few words, is that right? Let's do it. Okay.' The oath is administered: 'I, Marco Rubio, do solemnly swear, do solemnly swear, that I will support and defend, that I will support and defend, the Constitution of the United States, the Constitution of the United States, against all enemies, foreign and domestic. That I will bear true faith and allegiance to the same. That I will bear true faith and allegiance to the same. That I take this obligation freely. That I take this obligation freely. Without any mental reservation or purpose of evasion. Without any mental reservation or purpose of evasion. And that I will well and faithfully discharge. And that I will well and faithfully discharge. The duties of the office on which I am about to enter. The duty of the office on which I am about to enter. So help me God. So help me God. Congratulations, Mr. Secretary.'

Marco Rubio then addresses the audience: 'Thank you, Mr. Vice President, for making time. It's been a busy 72 hours, um, and uh, maybe longer, but the 96 hours, I guess. But um, first, I want to thank Janette, my wife, who has been so supportive of it as the Vice President knows well. It's impossible to do any of these jobs we do here, including the Senate, but now in this new role, uh, without the support of our family and and particularly of our spouses. And so, uh, thank you for being supportive every step of the way. I would not stand here before you today without that. I'm also thrilled and grateful that all four of my children are here. That the most important legacy any of us will leave behind, the most important job I'll ever have, is that of a father and a husband. And I'm honored that they are able to join us. Amanda, my oldest, Daniela, uh, my second, Anthony, our third, and then Dominic. Um, I'm very happy that they're able to see this today. I also want to thank my colleague, Senator Risch and Mrs. Risch for joining us. Um, he did a great job managing the committee, which uh brought us here to this point, but he's also been uh one of my closest friends in my time in the US Senate. In fact, we by reason of chance, certainly not by design, we wound up basically being first and second behind one another on seniority in every committee. So, we even sat next to each other on the floor. So, uh, people thought it was a plot, it was not by design, and uh, but it's one of the most special relationships I've established. And obviously, it's an honor to be with the Vice President, who um, I think is going to be phenomenal. It's one of someone I knew and admired and actually relied on for policy ideas before he was even elected to the Senate. And now we'll do an extraordinary job and uh for the president. And I can't think of a of a better voice for for the world and for the president's policies.'

Rubio continues: 'As far as the task ahead, the the it's uh, you know, President Trump was elected to keep promises, and he's going to keep those promises. And his primary promise when it comes to foreign policy is that the priority of the United States Department of State will be the United States. It will be furthering the national interest of this country. And he's given us a very clear mandate. President Trump's made it very clear everything we do, and I this is true in government, but especially at the Department of State, everything we do must be justified by the answer to one of three questions. Does it make us stronger? Does it make us safer? And does it make us more prosperous? If it doesn't do one of those three things, we will not do it. And and so uh that is the goal and that is the task and that is the promise that he was elected to keep, and that is the promise he will keep, and we will help him keep. It's a transformational moment. The United States, I think, is now uh as President Trump pointed out last night, and I believe deeply, we are headed into a new era that I think will make the world a safer place. We have a president who yesterday, President Trump made clear in his inaugural speech that one of the primary goals of American foreign policies is the promotion of peace. Of course, peace through strength, peace and always without uh abandoning our values. But I think it's extraordinary that it's something that needs to be said and hasn't been said enough in recent memory. And we look forward to being uh a key part of helping the president achieve his agenda that he has a clear mandate to keep.'

Rubio briefly switches to Spanish: 'If I may take the liberty for just 15 seconds uh to say something in Spanish, because I know a lot of people back home would be very proud, and I want to make sure I acknowledge that. Get a lot of like, gracias. Adios. A Dios. A mi familia. Uh, a mi familia que no esta aqui con nosotros hoy. A mis padres que vinieron en este pais en el ano 1956. Y el proposito de su vida fue que nosotros pudieramos vivir los suenos que no fueron posible para ellos. Es un honor increible ser el secretario de estado del pais mas poderoso y mas bueno en la historia de toda la humanidad. Es un gran honor y le doy las gracias al presidente Trump por esta oportunidad. I just said I saved the much money by switching to Geico. That's what I said. So.'

He closes by thanking God and President Trump, saying, 'I'm honored and I'm privileged. Cognizant of responsibility, and I want to thank President Trump for his confidence. We will work hard every second of the day to help him achieve the agenda the American people have given him to achieve. Thank you. Thanks for being a part of this today. God bless all of you. Thank you. Thank you, Mr. Secretary.' The video concludes with a promotional screen featuring a blue background with digital patterns, displaying 'SUBSCRIBE' and 'WATCH MORE' text, alongside a smaller inset video of three Fox News hosts seated on a couch in a studio setting.`,
  },
  {
    title: 'Recipe timeline grounding',
    task: 'Timestamped audio-visual captioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=1trMZ_5xQlU',
    embedUrl: 'https://www.youtube-nocookie.com/embed/1trMZ_5xQlU',
    prompt: 'Summarize the audio and visual events in the video with their corresponding start and end times.',
    response: `<v>0-3</v> A close-up shot shows several green bitter gourds (karela) stuffed with a brown, crumbly mixture, tied with white thread, arranged on a white plate. The text 'STUFFED KARELA' is overlaid on the video. <a>0-3</a> A female speaker says, "Stuffed Karela."
<v>3-6</v> The screen displays the ingredients list for the recipe. <a>3-6</a> No dialogue; silence.
<v>6-10</v> The screen displays the method for preparing the recipe. <a>6-10</a> No dialogue; silence.
<v>10-39</v> A woman in a black and white patterned top stands in a modern kitchen with red tiled walls, speaking to the camera. A black frying pan is on the stove in front of her. <a>10-39</a> The woman introduces herself as Jyotsna and explains that she will be teaching a recipe for stuffed Karela, a dish she started eating after her friend's mother's recipe.
<v>39-42</v> An overhead shot displays all the ingredients for the recipe arranged on a dark countertop. <a>39-42</a> The woman says, "For this recipe, the ingredients are as follows."
<v>42-45</v> A close-up shows two green bitter gourds (karela) in a clear glass bowl. The text '4-5 medium bitter gourds (karela)' is overlaid. <a>42-45</a> The woman says, "Bitter gourd or Karela."
<v>45-49</v> A close-up shows finely chopped red onions in a clear glass bowl. The text '2 medium onions, finely chopped' is overlaid. <a>45-49</a> The woman says, "This can be either the small ones or a medium sized ones."
<v>49-51</v> A close-up shows white yogurt in a clear glass bowl. The text '2 teaspoons yogurt' is overlaid. <a>49-51</a> The woman says, "Don't take the large ones."
<v>51-53</v> A close-up shows yellow turmeric powder in a clear glass bowl. The text '1/4 teaspoon turmeric powder' is overlaid. <a>51-53</a> The woman says, "Finely chopped onions."
<v>53-55</v> A close-up shows light brown coriander powder in a clear glass bowl. The text '1 teaspoon coriander powder' is overlaid. <a>53-55</a> The woman says, "Yogurt, that's the hi."
<v>55-57</v> A close-up shows light brown dried mango powder in a clear glass bowl. The text '1/2 teaspoon dried mango powder' is overlaid. <a>55-57</a> The woman says, "Turmeric powder."
<v>57-59</v> A close-up shows red chili powder in a clear glass bowl. The text '1/2 teaspoon red chilli powder' is overlaid. <a>57-59</a> The woman says, "Coriander powder."
<v>59-61</v> A close-up shows brown cumin powder in a clear glass bowl. The text '1/2 teaspoon cumin powder' is overlaid. <a>59-61</a> The woman says, "Amchur powder, that's dry mango powder."
<v>61-63</v> A close-up shows brown garam masala powder in a clear glass bowl. The text '1/2 teaspoon garam masala powder' is overlaid. <a>61-63</a> The woman says, "Red chili powder."
<v>63-65</v> A close-up shows white salt in a clear glass bowl. The text 'Salt to taste' is overlaid. <a>63-65</a> The woman says, "Cumin powder."
<v>65-67</v> A close-up shows clear cooking oil in a glass bottle. The text '2 teaspoons oil' is overlaid. <a>65-67</a> The woman says, "Garam masala powder."
<v>67-69</v> A close-up shows white salt in a clear glass bowl. The text 'Salt to taste' is overlaid. <a>67-69</a> The woman says, "Salt and oil."
<v>69-73</v> The woman stands in the kitchen, holding a bitter gourd and a knife, preparing to scrape it. <a>69-73</a> The woman says, "To make this recipe, we have to prepare the bitter gourd a bit."
<v>73-76</v> A close-up shows the woman's hands scraping the outer green skin off a bitter gourd with a knife on a wooden cutting board. <a>73-76</a> The woman says, "What we have to do is take these bitter gourd and scrape it."
<v>76-80</v> The woman continues scraping the bitter gourd, with small green pieces accumulating on the cutting board. <a>76-80</a> The woman says, "Mind you, don't throw the scrapings because we are going to use this for the stuffing."
<v>80-84</v> The woman makes a slit down the middle of the bitter gourd, then opens it up to reveal the white seeds inside. <a>80-84</a> The woman says, "Once the Karela has been scraped, we'll give it a slit in the middle and open it up."
<v>84-88</v> The woman removes the white seeds from the bitter gourd, leaving a hollowed-out cavity. <a>84-88</a> The woman says, "Take out the seeds that is inside."
<v>88-92</v> The woman holds up the hollowed bitter gourd, showing the gap created by the seeds removal. <a>88-92</a> The woman says, "Once we take these seeds out, we get a nice gap in the middle."
<v>92-96</v> The woman continues to remove the remaining seeds, ensuring the cavity is clean. <a>92-96</a> The woman says, "In which we'll be later on doing the stuffing."
<v>96-100</v> The woman sprinkles salt over the hollowed bitter gourd and gently rubs it to season. <a>96-100</a> The woman says, "You can keep these seeds also, if they are not too hard, to that will go into the stuffing."
<v>100-104</v> The woman places the salted bitter gourd into a clear glass bowl and sets it aside. <a>100-104</a> The woman says, "Now we have a nice gap in the middle."
<v>104-108</v> The woman adds more salt to the bitter gourd in the bowl and mixes it thoroughly. <a>104-108</a> The woman says, "Now what we are going to do to this Karela, which has been scraped and cut, we'll add some salt and keep it aside for about half an hour."
<v>108-112</v> The woman continues to mix the bitter gourd with salt, ensuring it is evenly coated. <a>108-112</a> The woman says, "You can nicely add some salt because later on once the water is out, we are going to drain this salt water."
<v>112-116</v> The woman adds sea salt to the bitter gourd and mixes it again. <a>112-116</a> The woman says, "You can even add some sea salt, that is mota namak, that will give a nice flavor to it."
<v>116-120</v> The woman continues to mix the bitter gourd with sea salt, ensuring thorough seasoning. <a>116-120</a> The woman says, "So we keep these aside."
<v>120-124</v> The woman holds up the bitter gourd, now seasoned with salt, and places it back into the bowl. <a>120-124</a> The woman says, "Now we've soaked this Karela for half an hour, it's let out some water."
<v>124-128</v> The woman squeezes the bitter gourd in the bowl to remove excess water, then transfers it to a white plate. <a>124-128</a> The woman says, "So we'll be draining out this water, squeezing it out."
<v>128-132</v> The woman continues to squeeze the bitter gourd, ensuring all the water is removed. <a>128-132</a> The woman says, "Some people who have diabetes can drink this juice in fact, but we don't need it for the recipe."
<v>132-136</v> The woman places the squeezed bitter gourd onto a white plate and sets it aside. <a>132-136</a> The woman says, "We'll take it out on another plate."
<v>136-140</v> The woman holds up the squeezed bitter gourd, now ready for frying. <a>136-140</a> The woman says, "Now we have this Karela which has been squeezed out."
<v>140-144</v> The woman places the bitter gourd on the plate and turns on the gas stove, heating a black frying pan. <a>140-144</a> The woman says, "We heat some oil for deep frying and we'll add the Karelas to this."
<v>144-148</v> The woman adds oil to the hot frying pan and places the bitter gourds into the oil for deep frying. <a>144-148</a> The woman says, "We fry these Karelas till they are golden brown."
<v>148-152</v> The bitter gourds sizzle and bubble in the hot oil as they fry. <a>148-152</a> Sizzling sounds are heard as the woman continues speaking.
<v>152-156</v> The woman uses a slotted spoon to turn the bitter gourds in the oil, ensuring even frying. <a>152-156</a> The woman says, "It doesn't take much time to fry these."
<v>156-160</v> The bitter gourds continue to fry in the oil, turning golden brown. <a>156-160</a> Sizzling sounds continue.
<v>160-164</v> The woman uses the slotted spoon to remove the golden-brown fried bitter gourds from the oil. <a>160-164</a> The woman says, "These stuffed Karelas can be used while traveling because they stay for a long time."
<v>164-168</v> The woman places the fried bitter gourds onto a plate lined with kitchen paper to drain excess oil. <a>164-168</a> Sizzling sounds continue.
<v>168-172</v> The woman continues to remove the fried bitter gourds from the oil and places them on the paper. <a>168-172</a> The woman says, "Now the Karelas have got a nice golden brown color and they're ready to be taken out."
<v>172-176</v> The woman removes the last of the fried bitter gourds from the oil and sets them aside. <a>172-176</a> The woman says, "Let's drain them and take them out on a kitchen napkin so that the excess oil gets drained."
<v>176-180</v> The woman holds up the fried bitter gourds, now ready for stuffing. <a>176-180</a> The woman says, "Now that our Karelas are ready to be stuffed, we need to make a stuffing, of course."
<v>180-184</v> The woman places the stuffed bitter gourds on a plate and turns on the gas stove, heating a black frying pan. <a>180-184</a> The woman says, "Let's heat a pan, take some oil."
<v>184-188</v> The woman pours oil into the hot frying pan and adds chopped onions to it. <a>184-188</a> The woman says, "Once the oil is hot, we'll add the chopped onions."
<v>188-192</v> The onions sizzle and saute in the oil, turning translucent. <a>188-192</a> Sizzling sounds are heard.
<v>192-196</v> The woman continues to saute the onions until they are golden brown. <a>192-196</a> The woman says, "The onions need to be sauteed till they are golden brown."
<v>196-200</v> The woman adds the scraped bitter gourd pieces to the sauteed onions in the pan. <a>196-200</a> The woman says, "Now the onions are half done, so we'll add the Karela scrapings."
<v>200-204</v> The woman mixes the scraped bitter gourd with the onions in the pan. <a>200-204</a> The woman says, "Not too much in proportion with the onions."
<v>204-208</v> The woman continues to mix the onions and scraped bitter gourd, ensuring they are well combined. <a>204-208</a> The woman says, "In case you have too many Karelas and the scrapings are a lot, you don't need to add all of it, probably equal to the onions."
<v>208-212</v> The woman covers the pan with a lid and cooks the mixture for two minutes. <a>208-212</a> The woman says, "Now we'll mix both these and saute them."
<v>212-216</v> The woman removes the lid from the pan, revealing the cooked mixture. <a>212-216</a> The woman says, "Let's cover this and cook it for just two minutes so that the rawness of the bitter gourd scrapings go away."
<v>216-220</v> The woman adds various spices to the cooked mixture in the pan. <a>216-220</a> The woman says, "Now our onion and bitter gourd mixture is almost done."
<v>220-224</v> The woman adds salt to the mixture and mixes it well. <a>220-224</a> The woman says, "Now we'll add all the masalas, a little bit of salt, just enough for the stuffing."
<v>224-228</v> The woman adds turmeric powder to the mixture and mixes it in. <a>224-228</a> The woman says, "Turmeric powder, coriander powder."
<v>228-232</v> The woman adds coriander powder to the mixture and mixes it in. <a>228-232</a> The woman says, "Cumin powder, red chili powder."
<v>232-236</v> The woman adds cumin powder to the mixture and mixes it in. <a>232-236</a> The woman says, "Garam masala powder, and amchur powder to make it tangy."
<v>236-240</v> The woman adds red chili powder to the mixture and mixes it in. <a>236-240</a> The woman says, "Give it a nice mix."
<v>240-244</v> The woman adds garam masala powder to the mixture and mixes it in. <a>240-244</a> The woman says, "Now we'll add the yogurt."
<v>244-248</v> The woman adds amchur powder to the mixture and mixes it in. <a>244-248</a> The woman says, "And we'll mix this stuffing, the yogurt will give out a little bit of water."
<v>248-252</v> The woman adds yogurt to the mixture and mixes it in. <a>248-252</a> The woman says, "So we'll saute it until it becomes dry."
<v>252-256</v> The woman continues to mix the stuffing, ensuring the yogurt is well incorporated. <a>252-256</a> The woman says, "Our stuffing is almost done."
<v>256-260</v> The woman continues to mix the stuffing, ensuring the yogurt is well incorporated. <a>256-260</a> The woman says, "We just going to dry off the excess water."
<v>260-264</v> The woman tastes the stuffing from a spoon, checking the seasoning. <a>260-264</a> The woman says, "Here you can adjust the seasoning, that is salt, you can taste the stuffing and see if the salt is enough."
<v>264-268</v> The woman continues to taste the stuffing, ensuring the seasoning is correct. <a>264-268</a> The woman says, "The yogurt gives a very nice flavor and it brings out all the flavors of the other ingredients."
<v>268-272</v> The woman continues to taste the stuffing, ensuring the seasoning is correct. <a>268-272</a> The woman says, "Our stuffing is now ready."
<v>272-276</v> The woman turns off the burner and lets the stuffing cool slightly. <a>272-276</a> The woman says, "Let's switch off the burner, cool it a little bit."
<v>276-280</v> The woman holds up the fried bitter gourds, now ready for stuffing. <a>276-280</a> The woman says, "We have our Karelas here, which have been fried."
<v>280-284</v> The woman takes a bitter gourd and begins to stuff it with the prepared mixture. <a>280-284</a> The woman says, "And now we'll be adding the stuffing into these gaps of the Karela."
<v>284-288</v> The woman continues to stuff the bitter gourd, ensuring the mixture is evenly distributed. <a>284-288</a> The woman says, "And then we'll be tying it with a thread."
<v>288-292</v> The woman ties the stuffed bitter gourd with a white thread, securing the stuffing inside. <a>288-292</a> The woman says, "It's not funny, it is true and it's done with Karelas all the time."
<v>292-296</v> The woman continues to tie the stuffed bitter gourd, ensuring the stuffing is secure. <a>292-296</a> The woman says, "Now let's stuff our Karelas."
<v>296-300</v> The woman takes another bitter gourd and begins to stuff it with the mixture. <a>296-300</a> The woman says, "Let's take a bit of the stuffing and let's fill it inside."
<v>300-304</v> The woman continues to stuff the bitter gourd, ensuring the mixture is evenly distributed. <a>300-304</a> The woman says, "If the stuffing is extra, doesn't matter, we'll use it in our vegetable later on."
<v>304-308</v> The woman ties the stuffed bitter gourd with a white thread, securing the stuffing inside. <a>304-308</a> The woman says, "Don't overstuff the Karelas, otherwise it'll all come out."
<v>308-312</v> The woman continues to tie the stuffed bitter gourd, ensuring the stuffing is secure. <a>308-312</a> The woman says, "So I'm stuffing them first and then I'll tie them up."
<v>312-316</v> The woman holds up the stuffed and tied bitter gourd, showing the final product. <a>312-316</a> The woman says, "Now our Karelas have been stuffed."
<v>316-320</v> The woman continues to tie the stuffed bitter gourd, ensuring the stuffing is secure. <a>316-320</a> The woman says, "The excess masala can remain in this pan, we'll use this for a final dish."
<v>320-324</v> The woman continues to tie the stuffed bitter gourd, ensuring the stuffing is secure. <a>320-324</a> The woman says, "We'll take a thread, we'll tie up the Karelas so that the stuffing doesn't come out."
<v>324-328</v> The woman continues to tie the stuffed bitter gourd, ensuring the stuffing is secure. <a>324-328</a> The woman says, "But remember, before serving, either you tell the people to open it up or you open it and then serve it."
<v>328-332</v> The woman continues to tie the stuffed bitter gourd, ensuring the stuffing is secure. <a>328-332</a> The woman says, "Just tie the thread across the cut that you've done for the stuffing."
<v>332-336</v> The woman continues to tie the stuffed bitter gourd, ensuring the stuffing is secure. <a>332-336</a> The woman says, "Our stuffed Karelas are now ready with all the thread."
<v>336-340</v> The woman continues to tie the stuffed bitter gourd, ensuring the stuffing is secure. <a>336-340</a> The woman says, "They just need a little bit of finishing touch."
<v>340-344</v> The woman continues to tie the stuffed bitter gourd, ensuring the stuffing is secure. <a>340-344</a> The woman says, "We'll use this pan which has the excess masala."
<v>344-348</v> The woman continues to tie the stuffed bitter gourd, ensuring the stuffing is secure. <a>344-348</a> The woman says, "You can add a little bit of oil, but I think it doesn't require."
<v>348-352</v> The woman continues to tie the stuffed bitter gourd, ensuring the stuffing is secure. <a>348-352</a> The woman says, "So we'll heat this masala."
<v>352-356</v> The woman continues to tie the stuffed bitter gourd, ensuring the stuffing is secure. <a>352-356</a> The woman says, "We'll add these stuffed and tied Karelas and let it cook in its own juices for about two to three minutes on slow flame."
<v>356-360</v> The woman continues to tie the stuffed bitter gourd, ensuring the stuffing is secure. <a>356-360</a> The woman says, "We can also cover it and just wait for two minutes before your Karelas are totally ready."
<v>360-364</v> The woman continues to tie the stuffed bitter gourd, ensuring the stuffing is secure. <a>360-364</a> The woman says, "Just toss the Karelas a bit."
<v>364-368</v> The woman continues to tie the stuffed bitter gourd, ensuring the stuffing is secure. <a>364-368</a> The woman says, "Our yummy stuffed Karelas are now ready."
<v>368-372</v> The woman continues to tie the stuffed bitter gourd, ensuring the stuffing is secure. <a>368-372</a> The woman says, "Let's take them out and serve them immediately."
<v>372-376</v> The woman continues to tie the stuffed bitter gourd, ensuring the stuffing is secure. <a>372-376</a> The woman says, "I'm going to serve it with the thread and inform the people who are going to eat it that each one can take the thread out on their own."
<v>376-380</v> The woman continues to tie the stuffed bitter gourd, ensuring the stuffing is secure. <a>376-380</a> The woman says, "It's good fun and exciting too."
<v>380-384</v> The woman continues to tie the stuffed bitter gourd, ensuring the stuffing is secure. <a>380-384</a> The woman says, "But I think the dish is even more exciting."
<v>384-388</v> The woman continues to tie the stuffed bitter gourd, ensuring the stuffing is secure. <a>384-388</a> The woman says, "Ready Karelas, stuffed and very very tasty."
<v>388-392</v> The woman continues to tie the stuffed bitter gourd, ensuring the stuffing is secure. <a>388-392</a> The woman says, "Enjoy."`,
  },
]
